services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    env_file:
      - .env
    container_name: mess_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mess_db_data:/var/lib/mysql

  backend:
    build: ./backend
    env_file:
      - .env
    container_name: mess_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=db
      - BACKEND_API_KEY=${BACKEND_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  flet_app:
    build: ./frontend_main
    env_file:
      - .env
    container_name: mess_flet
    ports:
      - "8550:8550"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: mess_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mess_db_data: